name: test1
description: "The kind hearts online learning platform for kids and teachers."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  provider: ^6.1.1
  firebase_auth: ^4.17.5
  fluttertoast: ^8.2.4
 
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^4.15.6
  equatable: ^2.0.5
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  custom_cupertino_picker: ^2.0.3
  image_picker: ^1.0.7
  # video_player: ^2.8.2
  firebase_storage: ^11.6.7
  # split_view: ^3.2.1
  # flutter_split_view: ^0.1.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  contained_tab_bar_view: ^0.8.0
  rxdart: ^0.26.0
  file_picker: ^6.2.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  geocoding: ^3.0.0
  geolocator: ^10.1.1
  google_maps_flutter: ^2.6.0
  google_maps_place_picker_mb: ^3.1.2
  animated_custom_dropdown: ^3.0.0
  dropdown_button2: ^2.3.9
  skeletonizer: ^1.1.1
  permission_handler: ^11.3.0
  loading_animation_widget: ^1.2.1
  flutter_slider_drawer: ^2.1.3
  like_button: ^2.0.5
  easy_loading_button: ^0.3.2
  expansion_tile_card: ^3.0.0
  map_launcher: ^3.2.0
  animated_toggle_switch: ^0.8.2
  calendar_slider: ^0.0.4
  searchbar_animation: ^0.0.4
  material_floating_search_bar_2: ^0.5.0
  alphabet_scroll_view: ^0.3.2
  profanity_filter: ^2.0.0
  fl_chart: ^0.67.0
  flutter_form_builder: ^9.2.1
  image_gallery_saver: ^2.0.3
  flame: ^1.17.0
  flame_tiled: ^1.20.1
  flame_audio: ^2.10.1
  csv: ^6.0.0


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: 
    generate: true
    image_path: "assets/icon/icon.png"
    adaptive_icon_background: "#000000"
  ios:
    generate: true
    remove_alpha_ios: true
    image_path: "assets/icon/icon.png"
    background_color_ios: "#000000"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FF0000"
    theme_color: "#FF0000"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FF0000"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FF0000"

  # The "flutter_lints" package below cont∏ains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensur–—s that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_images/
    - assets/images/games/1 Pink_Monster/
    - assets/images/games/2 Owlet_Monster/
    - assets/images/games/3 Dude_Monster/
    - assets/tiles/
    - assets/audio/
    - assets/images/Tileset-Terrain2.png
    - assets/images/trees.png
    - assets/images/backgrounds/pink_dodge/
    - assets/images/backgrounds/puzzle/
    - assets/images/backgrounds/words_juice/
    - assets/words.csv
    - assets/icon/icon.png

  fonts:
    - family: ValMore
      fonts:
        - asset: assets/Font/Planes_ValMore.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
