// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmJJaH1sc-cb6w1dXO0CS4pCOu27EsIfs',
    appId: '1:554131863030:web:52d839e86014bcb03b83d7',
    messagingSenderId: '554131863030',
    projectId: 'flutter-392e6',
    authDomain: 'flutter-392e6.firebaseapp.com',
    storageBucket: 'flutter-392e6.appspot.com',
    measurementId: 'G-2P58MJ0D3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPk0xy3Ce6dfgXoR7541x6ce9vDjg7wOU',
    appId: '1:554131863030:android:44abab06d59e71183b83d7',
    messagingSenderId: '554131863030',
    projectId: 'flutter-392e6',
    storageBucket: 'flutter-392e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuSdJS_nBh9_nTrKrYn0vVZfD8MVlhTA',
    appId: '1:554131863030:ios:931be22655497b9d3b83d7',
    messagingSenderId: '554131863030',
    projectId: 'flutter-392e6',
    storageBucket: 'flutter-392e6.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuSdJS_nBh9_nTrKrYn0vVZfD8MVlhTA',
    appId: '1:554131863030:ios:55169b25ebd907023b83d7',
    messagingSenderId: '554131863030',
    projectId: 'flutter-392e6',
    storageBucket: 'flutter-392e6.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
